version: "3"
services:
  web:
    build:
      context: "./web/"
    ports:
      - ${WEB_PORT}:8000
    tty: true
    depends_on:
      - app
    image: ${PROJECT_NAME}-web
    container_name: ${PROJECT_NAME}-web
    volumes:
      - ../static:/static

  app:
    build:
      context: "./app/"
    command: uwsgi --socket :8001 --file ./mysite/wsgi.py
    volumes:
      - '../src:/app'
      - '../static:/static'
    tty: true
    expose:
      - 8001
    depends_on:
      - db
    image: ${PROJECT_NAME}-app
    container_name: ${PROJECT_NAME}-app

  db:
    build:
      context: "./mysql/"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_HOST=127.0.0.1
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER_NAME}
      - MYSQL_PASSWORD=${USER_PASSWORD}
    ports:
        - ${DB_PORT}:3306
    image: ${PROJECT_NAME}-db
    container_name: ${PROJECT_NAME}-db
